# prometheus.yml
global:
  scrape_interval: 30s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'speedtest'
    static_configs:
      - targets: ['speedtest:9798']
    scrape_interval: 6h
    scrape_timeout: 1m
  - job_name: 'esp32_1'
    static_configs:
      - targets: ['192.168.0.182']
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets: ['alertmanager:9093']
#rule_files:
#  - 'alert.rules'
